

/* Create THPL FROM DDDEZ after stage 1 and run this */
DROP TABLE IF EXISTS admin
DROP TABLE IF EXISTS OIGList
DROP TABLE IF EXISTS ATCrelationships
DROP TABLE IF ExISTS billingregions
DROP TABLE IF Exists cal
DROP TABLE IF EXISTS calcHba
DROP TABLE IF EXISTS calcHbc
DROP TABLE IF EXISTS calcHid
DROP TABLE IF EXISTS calcHpd
DROP TABLE IF EXISTS calcHAb
DROP TABLE IF EXISTS calcrrb
DROP TABLE IF EXISTS co
DROP TABLE IF EXISTS svco
DROP TABLE IF EXISTS svra
DROP TABLE IF EXISTS svradt
DROP TABLE IF EXISTS u
